### ISSUE TITLE
Plugin disabled automatically due to error

### ISSUE THREAD

**Issue by ghost** [MatteoManna/Simple-User-Avatar#5]
Hi. The plugins stopped working on the latest update, 2.4, released 2 hours ago, and the following message appeared inside a red box on the Plugins page:

"The simple-user-avatar/index.php was disabled due to an error: The plugin does not have a valid header."

The plugins also has deprecated code, which is listed on the bottom of this page:
https://plugintests.com/plugins/wporg/simple-user-avatar/latest

**Comment by MatteoManna** [comment]
Hi @marceloaof , I released version 2.5. I hope I fix every bug.

**Comment by ghost** [comment]
Hi @MatteoManna how lucky the world is to receive your work. It is working again. Thank you 😘
