### ISSUE TITLE
Some avatars not showing in mobile

### ISSUE THREAD

**Issue by IngerJohnsson** [MatteoManna/Simple-User-Avatar#6]
I have a problem with some avatars not showing in mobile. All avatars are showing in desktop, all browsers.

- I've both tried to clear the mobile cache and tried to switch between different types of standard profile picture settings, both blank, myesterious person, gravatar... etc with no effect.

- In desktop I've visited the page both logged in as an administrator and as a regular visitor.

- All users have exactly the same type of settings and all have the same roles.

Does anyone have a solution to this problem
![avatar-mobile](https://user-images.githubusercontent.com/32107147/151789607-6adf2a21-c745-459a-953e-15851a6a57f5.jpg)
![avatar-desktop](https://user-images.githubusercontent.com/32107147/151789610-9b5c7480-e7ce-414d-a0c2-875f0c4c9f96.jpg)
?

**Comment by MatteoManna** [comment]
Hi @IngerJohnsson,
thank you for your message. I check this issue and I think there isn't this bug in latest version.

Matteo
